version: 2
sources:
  - name: raw
    database: dbt-serenerbas-503714
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Raw sales order information
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
          - dbt_utils.unique_combination_of_columns:
             arguments:
               combination_of_columns:
                 - orders_id
                 - pdt_id
        columns:
          - name: orders_id
            description: Unique identifier of the order
            tests:
              - not_null
          - name: pdt_id 
            description: Unique identifier of the product
            tests:
              - not_null
        config:
          freshness:
            warn_after:
             count: 90
             period: day
          loaded_at_field: CAST(date_date AS TIMESTAMP)

      - name: product
        identifier: raw_gz_product
        description: Raw product information
        columns:
          - name: products_id
            description: unique identifier of the product
            tests:
              - unique
              - not_null
             
      - name: ship
        identifier: raw_gz_ship
        description: Raw shipping and logistics data
        columns:
          - name: orders_id
            description: unique identifier of the shipment
            tests:
              - unique
              - not_null
